name: build Micropython

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

env:
  BUILD_DEPS: |
    cmake
    gcc-arm-none-eabi
    libnewlib-arm-none-eabi
    build-essential
    libreadline-dev
    libffi-dev
    pkg-config
    libstdc++-arm-none-eabi-newlib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends $BUILD_DEPS

      - name: Checkout Micropython Sources
        uses: actions/checkout@v3
        with:
          repository: "micropython/micropython"
          ref: "master"
          submodules: "true"
          path: "micropython"

      - name: Build Submodules
        run: |
          cd micropython
          make -j$(nproc) -C ports/rp2 submodules

      - name: Build mpy-cross
        run: |
          cd micropython
          make -j$(nproc) -C mpy-cross

      - name: Build Firmware (rp2)
        run: |
          cd micropython/ports/rp2
          make -j$(nproc)

      - name: DEBUG - Show firmware Files
        run: |
          cd micropython/ports/rp2/build-PICO
          ls -l
